name: Accessibility Issue
description: Report accessibility barriers found during UAT testing
title: "[A11Y] "
labels: ["accessibility", "uat", "wcag", "needs-triage"]
assignees:
  - 
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting an accessibility issue! This helps us create inclusive experiences for all users.

  - type: input
    id: summary
    attributes:
      label: Summary
      description: Brief description of the accessibility barrier
      placeholder: ex. Form inputs missing labels for screen readers
    validations:
      required: true

  - type: dropdown
    id: wcag_guideline
    attributes:
      label: WCAG 2.2 Guideline
      description: Which WCAG guideline is violated?
      options:
        - "1.1 Text Alternatives"
        - "1.2 Time-based Media"
        - "1.3 Adaptable"
        - "1.4 Distinguishable"
        - "2.1 Keyboard Accessible"
        - "2.2 Enough Time"
        - "2.3 Seizures and Physical Reactions"
        - "2.4 Navigable"
        - "2.5 Input Modalities"
        - "3.1 Readable"
        - "3.2 Predictable"
        - "3.3 Input Assistance"
        - "4.1 Compatible"
        - "Unknown/Multiple"
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: Impact severity for users with disabilities
      options:
        - Critical - Completely blocks access for affected users
        - High - Severely limits functionality for affected users
        - Medium - Creates barriers but workarounds possible
        - Low - Minor inconvenience, good practices improvement
      default: 1
    validations:
      required: true

  - type: checkboxes
    id: user_impact
    attributes:
      label: User Impact
      description: Which users are affected? (Select all that apply)
      options:
        - label: Screen reader users (NVDA, JAWS, VoiceOver)
        - label: Keyboard-only users
        - label: Users with low vision
        - label: Users with color blindness
        - label: Users with motor disabilities
        - label: Users with cognitive disabilities
        - label: All users

  - type: input
    id: environment
    attributes:
      label: Environment & Assistive Technology
      description: Browser, OS, and assistive technology used
      placeholder: ex. NVDA 2023.1, Firefox 118, Windows 11
    validations:
      required: true

  - type: textarea
    id: reproduce_steps
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the accessibility issue
      placeholder: |
        1. Navigate to the form using Tab key
        2. Try to identify input field purpose with screen reader
        3. Observe lack of label announcement
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Accessible Behavior
      description: What should happen for accessibility compliance?
      placeholder: Screen reader should announce the input field purpose and any validation requirements
    validations:
      required: true

  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual Behavior
      description: What actually happens that creates the barrier?
      placeholder: Screen reader only announces "Edit text" without context
    validations:
      required: true

  - type: textarea
    id: suggested_fix
    attributes:
      label: Suggested Fix
      description: Recommended solution for the accessibility issue
      placeholder: |
        - Add proper labels using <label> elements or aria-label
        - Ensure form validation errors are announced
        - Test with screen readers to verify fix

  - type: dropdown
    id: testing_method
    attributes:
      label: Testing Method
      description: How was this accessibility issue discovered?
      options:
        - Manual screen reader testing
        - Keyboard navigation testing
        - Automated accessibility scanning (axe, WAVE)
        - Color contrast testing
        - Zoom/magnification testing
        - Usability testing with users with disabilities
      default: 0
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Screenshots/Videos & Additional Context
      description: Visual evidence and any other relevant information
      placeholder: |
        - Screenshots of the issue
        - Screen reader output/logs
        - Color contrast measurements
        - Related WCAG success criteria

  - type: checkboxes
    id: accessibility_checklist
    attributes:
      label: Accessibility Testing Checklist
      description: Confirm testing completeness
      options:
        - label: Tested with at least one screen reader
        - label: Tested keyboard navigation
        - label: Verified color contrast ratios
        - label: Checked for proper heading structure
        - label: Validated HTML semantics